# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title An Rcpp function to quickly perform weighted linear regression
#' @name fastwLm
#'
#' @param x design matrix
#' @param y numeric vector of response variables
#' @param w numeric vector of weights
#' @return list
#' @export
#' @useDynLib blblm
#' @importFrom Rcpp sourceCpp
NULL

fastwLm <- function(X, y, w) {
    .Call('_blblm_fastwLm', PACKAGE = 'blblm', X, y, w)
}

